#!/bin/bash

nice /usr/local/bin/vinayaka-model-collector-impl 6 400
nice /usr/local/bin/vinayaka-model-collector-impl 9 400
nice /usr/local/bin/vinayaka-model-collector-impl 12 400
nice /usr/local/bin/vinayaka-super-model-collector-impl

