#!/bin/bash

nice /usr/local/bin/vinayaka-user-words-impl 3 400 &
sleep 1m
nice /usr/local/bin/vinayaka-user-words-impl 6 400 &
sleep 1m
nice /usr/local/bin/vinayaka-user-words-impl 9 400 &
wait

nice /usr/local/bin/vinayaka-user-words-impl 12 400 &
sleep 1m
nice /usr/local/bin/vinayaka-user-words-impl 15 400 &
sleep 1m
nice /usr/local/bin/vinayaka-user-words-impl 18 400
wait

